# This is a config for E2B sandbox template.
# You can use 'template_id' (10n5biegk00ute5arg79) or 'template_name (weirdlookingjay-nextjs-developer) from this config to spawn a sandbox:

# Python SDK
# from e2b import Sandbox
# sandbox = Sandbox(template='weirdlookingjay-nextjs-developer')

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create({ template: 'weirdlookingjay-nextjs-developer' })

start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "weirdlookingjay-nextjs-developer"
template_id = "10n5biegk00ute5arg79"
